# This configuration was used Ebert to review the ElixirOttawaMeetup/ring-my-bell-ex repository
# on 96917ca8ec6b49edd88a4bf82cf4b6f370d64953.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://docs.ebertapp.io/configuration and see the configuration
# details.
---
styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
- config
- test
- assets/css/phoenix.css
- assets/brunch-config.js
